### ISSUE TITLE
Compiler Warnings in md.c?

### ISSUE THREAD

**Issue by ProfessorSil** [Dion-Systems/metadesk#11]
This could totally be something I am doing wrong, but when trying to get set up with metadesk this afternoon, it seems like there are some compiler warnings in md.c that aren't caused by my usage
![image](https://user-images.githubusercontent.com/4468838/154389148-62e66edd-6cc2-4963-8886-158ce9bd79b2.png)
Warnings 4244, 4457, and 4456 on lines 1027, 1463, 1711, 1779, 3409, 3515, 3783, 3855, and 4022.
I just cloned the repository today. I'm using the VS2015 C++ compiler (with /W4 but with warnings 4130, 4201, 4324, 4458, 4505, 4996, and 4127 disabled so these warnings may also be present but I'm not seeing them).

Let me know if you want any more info or if it's potentially just my own mistakes or something.

**Comment by ryanfleury** [comment]
I think this is caused by the extra warnings you have enabled with /W4, which we generally do not enable. We aren't going to avoid all possible warnings in all possible configurations, but I'd be open to sanitizing the Metadesk code against some of the more common ones.

Just to double check, does a clean build without /W4 work in your configuration? I am testing both x64 and x86 builds locally, but only on 2017 and 2019.

As a workaround for now, you can disable the relevant warnings before `#include`ing Metadesk (then re-enable them afterwards), or just build Metadesk separately with separate options and link to it.

**Comment by ProfessorSil** [comment]
Yup it compiles if I don't specify a warning level. At W2 it's also is fine. Warning 4244 is enabled by warning level 3. And the other two come from level 4. I personally think warning 4244 can provide some use which is why I keep it enabled and adhere to it. It's also really easy to fix by adding an explicit cast. The other two warnings I'm not sure I've seen before and I don't know if I really care for them but I think that keeping names within a scope unique is probably not a bad idea.

**Comment by ryanfleury** [comment]
I updated `master` to be robust against /W4 warnings (only omitting some of the ones that you have disabled). Let me know if anything else comes up.
